"""add cart item removed_at

Revision ID: 18e547e2ee9a
Revises: e2afc90bf43e
Create Date: 2026-09-04 09:38:47.907103

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "18e547e2ee9a"
down_revision: str | Sequence[str] | None = "e2afc90bf43e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cartitem", schema=None) as batch_op:
        batch_op.add_column(sa.Column("removed_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cartitem", schema=None) as batch_op:
        batch_op.drop_column("removed_at")

    # ### end Alembic commands ###
