"""add_notify_price_increase_and_notification_log

Revision ID: 2ee4cd13e56d
Revises: 4afcb7f7597a
Create Date: 2026-06-25 01:43:20.610600

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2ee4cd13e56d"
down_revision: str | Sequence[str] | None = "4afcb7f7597a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "notify_price_increase",
                sa.Boolean(),
                nullable=False,
                server_default="1",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.drop_column("notify_price_increase")

    # ### end Alembic commands ###
