"""add game aliases for merged ids

Revision ID: 82039870f353
Revises: e7a1c9d2f480
Create Date: 2026-08-11 07:45:35.035357

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "82039870f353"
down_revision: str | Sequence[str] | None = "e7a1c9d2f480"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gamealias",
        sa.Column("old_game_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.PrimaryKeyConstraint("old_game_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("gamealias")
    # ### end Alembic commands ###
