"""add_notify_out_of_stock

Revision ID: adda30f35926
Revises: 2ee4cd13e56d
Create Date: 2026-06-25 11:55:46.790386

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "adda30f35926"
down_revision: str | Sequence[str] | None = "2ee4cd13e56d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "notify_out_of_stock",
                sa.Boolean(),
                nullable=False,
                server_default="1",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.drop_column("notify_out_of_stock")

    # ### end Alembic commands ###
