"""add product groups and merge rejections

Revision ID: cf8c412c034e
Revises: 927dd94505e0
Create Date: 2026-08-10 22:30:59.745032

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "cf8c412c034e"
down_revision: str | Sequence[str] | None = "927dd94505e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productgroup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("bgg_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mergerejection",
        sa.Column("product_a_id", sa.Integer(), nullable=False),
        sa.Column("product_b_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_a_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_b_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("product_a_id", "product_b_id"),
    )
    # SQLite batch mode recreates the table, so the foreign key needs an
    # explicit name — an unnamed constraint can't be re-emitted or dropped.
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_product_group_id", "productgroup", ["group_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_constraint("fk_product_group_id", type_="foreignkey")
        batch_op.drop_column("group_id")

    op.drop_table("mergerejection")
    op.drop_table("productgroup")
    # ### end Alembic commands ###
