"""add store listing urls

A store's one `collection_path` becomes rows in `storeurl`, so a shop that
splits its catalog across several category pages can sync all of them.

The structural half was autogenerated; the backfill can't be, and the generated
drop of `store.collection_path` was softened to a nullable column so the old
value survives a downgrade. `env.py` lists the retired column so later
autogenerate runs stop proposing the drop again.

Revision ID: d28c5a26e70a
Revises: 18e547e2ee9a
Create Date: 2026-09-16 10:11:07.483346

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d28c5a26e70a"
down_revision: str | Sequence[str] | None = "18e547e2ee9a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Trailing slashes are cosmetic on a category URL, so they're stripped to keep
#: `/games` and `/games/` from becoming two rows for one page.
_NORMALIZED = "COALESCE(NULLIF(RTRIM(collection_path, '/'), ''), '/')"


def upgrade() -> None:
    op.create_table(
        "storeurl",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.String(), nullable=False),
        sa.Column("collection_path", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["store_id"], ["store.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("store_id", "collection_path"),
    )
    with op.batch_alter_table("storeurl", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_storeurl_store_id"), ["store_id"], unique=False
        )

    # Guarded so a partial run repeats safely.
    op.get_bind().execute(
        sa.text(
            f"""
            INSERT INTO storeurl (store_id, collection_path, enabled, created_at)
            SELECT id, {_NORMALIZED}, 1, CURRENT_TIMESTAMP
            FROM store
            WHERE NOT EXISTS (
                SELECT 1 FROM storeurl u WHERE u.store_id = store.id
            )
            """
        )
    )

    # Kept rather than dropped: the value is the only record of what a store
    # synced before this split.
    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.alter_column(
            "collection_path", existing_type=sa.VARCHAR(), nullable=True
        )


def downgrade() -> None:
    op.get_bind().execute(
        sa.text(
            """
            UPDATE store SET collection_path = COALESCE(
                (SELECT u.collection_path FROM storeurl u
                 WHERE u.store_id = store.id ORDER BY u.id LIMIT 1),
                collection_path,
                '/collections/board-games'
            )
            """
        )
    )

    with op.batch_alter_table("store", schema=None) as batch_op:
        batch_op.alter_column(
            "collection_path",
            existing_type=sa.VARCHAR(),
            nullable=False,
            existing_server_default=sa.text("'/collections/board-games'"),
        )

    with op.batch_alter_table("storeurl", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_storeurl_store_id"))

    op.drop_table("storeurl")
