"""add cart items

Revision ID: e2afc90bf43e
Revises: 678c5469faf6
Create Date: 2026-09-01 16:45:27.078418

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e2afc90bf43e"
down_revision: str | Sequence[str] | None = "678c5469faf6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cartitem",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(), nullable=False),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("added_price", sa.Float(), nullable=True),
        sa.Column("purchased_at", sa.DateTime(), nullable=True),
        sa.Column("purchased_price", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["game.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("cartitem", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_cartitem_game_id"), ["game_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cartitem", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cartitem_game_id"))

    op.drop_table("cartitem")
    # ### end Alembic commands ###
