"""split game from listing

`productgroup` becomes `game`, and every listing gets one. Game-level state
(name, BGG link, hidden, note, watch) moves off the listing and onto the game;
listings keep only what a shop reports — url, image, stock, price snapshots.

Renames and data moves can't be autogenerated, so the structural half was
generated and then adjusted to rename rather than drop/create. Price snapshots
are never touched. Legacy columns are dropped only after their values have been
copied onto the game, so downgrade restores the shape but not the data.

Revision ID: e7a1c9d2f480
Revises: b91d4e07c5aa
Create Date: 2026-08-10 23:20:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e7a1c9d2f480"
down_revision: str | Sequence[str] | None = "b91d4e07c5aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.rename_table("productgroup", "game")

    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("hidden", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column("note", sa.String(), nullable=True))

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.alter_column("group_id", new_column_name="game_id")

    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.add_column(sa.Column("game_id", sa.Integer(), nullable=True))

    with op.batch_alter_table("notificationlog", schema=None) as batch_op:
        batch_op.add_column(sa.Column("game_id", sa.Integer(), nullable=True))

    op.create_table(
        "watchlistingstate",
        sa.Column("watch_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("last_notified_price", sa.Float(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"]),
        sa.ForeignKeyConstraint(["watch_id"], ["watchlistitem.id"]),
        sa.PrimaryKeyConstraint("watch_id", "product_id"),
    )

    _backfill()

    # Legacy columns, now that everything they held lives on the game.
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("bgg_id")
        batch_op.drop_column("hidden")
        batch_op.alter_column("game_id", existing_type=sa.INTEGER(), nullable=False)
        # The renamed column kept the old constraint name; replace it.
        batch_op.drop_constraint("fk_product_group_id", type_="foreignkey")
        batch_op.create_foreign_key("fk_product_game_id", "game", ["game_id"], ["id"])

    with op.batch_alter_table("productoverride", schema=None) as batch_op:
        batch_op.drop_column("title")
        batch_op.drop_column("bgg_id")
        batch_op.drop_column("note")

    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.drop_column("product_id")
        batch_op.drop_column("last_notified_price")
        batch_op.alter_column("game_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_foreign_key(
            "fk_watchlistitem_game_id", "game", ["game_id"], ["id"]
        )

    with op.batch_alter_table("notificationlog", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_notificationlog_game_id", "game", ["game_id"], ["id"]
        )

    # One active watch per game.
    op.create_index(
        "ix_watchlistitem_active_game",
        "watchlistitem",
        ["game_id"],
        unique=True,
        sqlite_where=sa.text("active = 1"),
    )
    op.create_index("ix_product_game_id", "product", ["game_id"])


def _backfill() -> None:
    """Give every listing a game and move game-level state onto it.

    A first install has one store and no merges, so this is the path that turns
    the whole catalog into games. Each step is guarded so a partial run repeats
    safely.
    """
    bind = op.get_bind()

    # Never-merged listings each become their own game. A user's corrections
    # (renamed title, BGG link, note) are exactly what the game should carry.
    rows = bind.execute(
        sa.text(
            """
            SELECT p.id, p.title, p.bgg_id, p.hidden,
                   o.title AS ov_title, o.bgg_id AS ov_bgg_id, o.note AS ov_note
            FROM product p
            LEFT JOIN productoverride o ON o.product_id = p.id
            WHERE p.game_id IS NULL
            """
        )
    ).fetchall()

    for row in rows:
        result = bind.execute(
            sa.text(
                "INSERT INTO game (title, bgg_id, hidden, note, created_at)"
                " VALUES (:title, :bgg_id, :hidden, :note, CURRENT_TIMESTAMP)"
            ),
            {
                "title": (row.ov_title or row.title or "").strip() or "Untitled",
                "bgg_id": row.ov_bgg_id if row.ov_bgg_id is not None else row.bgg_id,
                "hidden": 1 if row.hidden else 0,
                "note": row.ov_note,
            },
        )
        bind.execute(
            sa.text("UPDATE product SET game_id = :game_id WHERE id = :product_id"),
            {"game_id": result.lastrowid, "product_id": row.id},
        )

    # Merged games: adopt a member's BGG link when the members agree, and hide
    # the game if any of its listings was hidden.
    bind.execute(
        sa.text(
            """
            UPDATE game SET bgg_id = (
                SELECT MIN(p.bgg_id) FROM product p
                WHERE p.game_id = game.id AND p.bgg_id IS NOT NULL
            )
            WHERE bgg_id IS NULL
              AND (SELECT COUNT(DISTINCT p.bgg_id) FROM product p
                   WHERE p.game_id = game.id AND p.bgg_id IS NOT NULL) = 1
            """
        )
    )
    bind.execute(
        sa.text(
            """
            UPDATE game SET hidden = 1
            WHERE hidden = 0
              AND EXISTS (SELECT 1 FROM product p
                          WHERE p.game_id = game.id AND p.hidden = 1)
            """
        )
    )
    bind.execute(
        sa.text(
            """
            UPDATE game SET note = (
                SELECT MIN(o.note) FROM productoverride o
                JOIN product p ON p.id = o.product_id
                WHERE p.game_id = game.id AND o.note IS NOT NULL
            )
            WHERE note IS NULL
            """
        )
    )

    # Watches follow the game of the listing they were created from.
    bind.execute(
        sa.text(
            """
            UPDATE watchlistitem SET game_id = (
                SELECT p.game_id FROM product p WHERE p.id = watchlistitem.product_id
            )
            WHERE game_id IS NULL AND product_id IS NOT NULL
            """
        )
    )

    # Per-listing alert memory starts from the single value it replaces, so the
    # next sync doesn't re-announce prices the user already saw.
    bind.execute(
        sa.text(
            """
            INSERT INTO watchlistingstate (watch_id, product_id, last_notified_price, updated_at)
            SELECT w.id, w.product_id, w.last_notified_price, CURRENT_TIMESTAMP
            FROM watchlistitem w
            WHERE w.product_id IS NOT NULL
              AND NOT EXISTS (
                  SELECT 1 FROM watchlistingstate s
                  WHERE s.watch_id = w.id AND s.product_id = w.product_id
              )
            """
        )
    )

    # Watches on listings that were already merged collapse onto one game: keep
    # the oldest, retire the rest, so the unique index below holds.
    bind.execute(
        sa.text(
            """
            UPDATE watchlistitem SET active = 0
            WHERE active = 1 AND game_id IS NOT NULL AND id > (
                SELECT MIN(w2.id) FROM watchlistitem w2
                WHERE w2.game_id = watchlistitem.game_id AND w2.active = 1
            )
            """
        )
    )

    # Watches whose listing vanished have no game to point at.
    bind.execute(sa.text("DELETE FROM watchlistitem WHERE game_id IS NULL"))

    bind.execute(
        sa.text(
            """
            UPDATE notificationlog SET game_id = (
                SELECT p.game_id FROM product p WHERE p.id = notificationlog.product_id
            )
            WHERE game_id IS NULL AND product_id IS NOT NULL
            """
        )
    )


def downgrade() -> None:
    """Restores the old shape. Values that moved onto the game are not restored."""
    op.drop_index("ix_product_game_id", table_name="product")
    op.drop_index("ix_watchlistitem_active_game", table_name="watchlistitem")
    op.drop_table("watchlistingstate")

    with op.batch_alter_table("notificationlog", schema=None) as batch_op:
        batch_op.drop_constraint("fk_notificationlog_game_id", type_="foreignkey")
        batch_op.drop_column("game_id")

    with op.batch_alter_table("watchlistitem", schema=None) as batch_op:
        batch_op.drop_constraint("fk_watchlistitem_game_id", type_="foreignkey")
        batch_op.add_column(sa.Column("product_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("last_notified_price", sa.Float(), nullable=True))
        batch_op.drop_column("game_id")

    with op.batch_alter_table("productoverride", schema=None) as batch_op:
        batch_op.add_column(sa.Column("title", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("bgg_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("note", sa.String(), nullable=True))

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_constraint("fk_product_game_id", type_="foreignkey")
        batch_op.add_column(sa.Column("bgg_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("hidden", sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.alter_column("game_id", new_column_name="group_id", nullable=True)

    with op.batch_alter_table("game", schema=None) as batch_op:
        batch_op.drop_column("note")
        batch_op.drop_column("hidden")

    op.rename_table("game", "productgroup")
