"""add shelves

Revision ID: f6177abb5e7f
Revises: d5e6f7a8b9c0
Create Date: 2026-06-18 12:22:27.000551

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f6177abb5e7f"
down_revision: str | Sequence[str] | None = "d5e6f7a8b9c0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shelf",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.String(), nullable=False),
        sa.Column("filters", sa.String(), nullable=True),
        sa.Column("sorts", sa.String(), nullable=True),
        sa.Column("built_in", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shelf")
    # ### end Alembic commands ###
